plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - ./DAM_2023/Database.md
  - ./DAM_2023/Artifact.md
  - ./DAM_2023/Experiments.md
  - ./index.md

theme: jekyll-theme-slate
